# Generated by Django 6.0.5 on 2026-05-30 19:14

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_date', models.DateField(verbose_name='Дата заезда')),
                ('check_out_date', models.DateField(verbose_name='Дата выезда')),
                ('status', models.CharField(choices=[('pending', 'Ожидает оплаты'), ('confirmed', 'Подтверждено (Оплачено)'), ('canceled', 'Отменено')], default='pending', max_length=30, verbose_name='Статус')),
                ('booking_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания брони')),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Итоговая стоимость')),
            ],
            options={
                'verbose_name': 'Бронирование',
                'verbose_name_plural': 'Бронирования',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название категории')),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from='name', unique=True, verbose_name='URL (Слаг)')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание')),
                ('max_guests', models.PositiveIntegerField(verbose_name='Макс. гостей')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Базовая цена')),
            ],
            options={
                'verbose_name': 'Категория номера',
                'verbose_name_plural': 'Категории номеров',
            },
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Основной гость')),
                ('check_in_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата заселения')),
                ('special_requests', models.TextField(blank=True, null=True, verbose_name='Особые пожелания')),
            ],
            options={
                'verbose_name': 'Список проживающих',
                'verbose_name_plural': 'Списки проживающих',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма')),
                ('yookassa_payment_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='ID платежа ЮKassa')),
                ('payment_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата оплаты')),
                ('payment_type', models.CharField(default='yookassa', max_length=50, verbose_name='Способ оплаты')),
                ('status', models.CharField(choices=[('pending', 'Ожидание'), ('paid', 'Оплачено'), ('canceled', 'Отменено')], default='pending', max_length=30, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Оплата',
                'verbose_name_plural': 'Оплаты',
            },
        ),
        migrations.CreateModel(
            name='Placement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_date', models.DateField(verbose_name='План. заезд')),
                ('check_out_date', models.DateField(verbose_name='План. выезд')),
                ('guests_count', models.PositiveIntegerField(verbose_name='Кол-во гостей')),
                ('price_per_night', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена за ночь (фикс.)')),
                ('check_in_fact', models.DateTimeField(blank=True, null=True, verbose_name='Фактический заезд')),
                ('check_out_fact', models.DateTimeField(blank=True, null=True, verbose_name='Фактический выезд')),
                ('status', models.CharField(choices=[('waiting', 'Ожидает заезда'), ('active', 'Проживает'), ('finished', 'Выехал')], default='waiting', max_length=30, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Размещение',
                'verbose_name_plural': 'Размещения',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=10, unique=True, verbose_name='Номер комнаты')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена за сутки')),
                ('image', models.ImageField(blank=True, null=True, upload_to='rooms/', verbose_name='Изображение номера')),
                ('amenities', models.TextField(blank=True, null=True, verbose_name='Удобства')),
                ('features', models.CharField(blank=True, max_length=255, null=True, verbose_name='Особенности')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Рейтинг')),
                ('rules', models.TextField(verbose_name='Правила проживания')),
                ('status', models.CharField(choices=[('available', 'Свободен'), ('occupied', 'Занят'), ('maintenance', 'На уборке/ремонте')], default='available', max_length=30, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Номер',
                'verbose_name_plural': 'Номерной фонд',
            },
        ),
    ]
