# Generated by Django 6.0.5 on 2026-05-19 08:25

import autoslug.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'verbose_name': 'Бронирование', 'verbose_name_plural': 'Бронирования'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория номера', 'verbose_name_plural': 'Категории номеров'},
        ),
        migrations.AlterModelOptions(
            name='guest',
            options={'verbose_name': 'Список проживающих', 'verbose_name_plural': 'Списки проживающих'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': 'Оплата', 'verbose_name_plural': 'Оплаты'},
        ),
        migrations.AlterModelOptions(
            name='placement',
            options={'verbose_name': 'Размещение', 'verbose_name_plural': 'Размещения'},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'verbose_name': 'Номер', 'verbose_name_plural': 'Номерной фонд'},
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания брони'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='check_in_date',
            field=models.DateField(verbose_name='Дата заезда'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='check_out_date',
            field=models.DateField(verbose_name='Дата выезда'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает оплаты'), ('confirmed', 'Подтверждено (Оплачено)'), ('canceled', 'Отменено')], default='pending', max_length=30, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Итоговая стоимость'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL, verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='category',
            name='base_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Базовая цена'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='category',
            name='max_guests',
            field=models.PositiveIntegerField(verbose_name='Макс. гостей'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Название категории'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from='name', unique=True, verbose_name='URL (Слаг)'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='check_in_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата заселения'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='is_primary',
            field=models.BooleanField(default=False, verbose_name='Основной гость'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='placement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guests', to='hotel.placement', verbose_name='Размещение'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='special_requests',
            field=models.TextField(blank=True, null=True, verbose_name='Особые пожелания'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest_records', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='hotel.booking', verbose_name='Бронь'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата оплаты'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(max_length=50, verbose_name='Способ оплаты'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидание'), ('paid', 'Оплачено'), ('failed', 'Ошибка')], default='pending', max_length=30, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='placement',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placements', to='hotel.booking', verbose_name='Бронь'),
        ),
        migrations.AlterField(
            model_name='placement',
            name='check_in_date',
            field=models.DateField(verbose_name='План. заезд'),
        ),
        migrations.AlterField(
            model_name='placement',
            name='check_in_fact',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Фактический заезд'),
        ),
        migrations.AlterField(
            model_name='placement',
            name='check_out_date',
            field=models.DateField(verbose_name='План. выезд'),
        ),
        migrations.AlterField(
            model_name='placement',
            name='check_out_fact',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Фактический выезд'),
        ),
        migrations.AlterField(
            model_name='placement',
            name='guests_count',
            field=models.PositiveIntegerField(verbose_name='Кол-во гостей'),
        ),
        migrations.AlterField(
            model_name='placement',
            name='price_per_night',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена за ночь (фикс.)'),
        ),
        migrations.AlterField(
            model_name='placement',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placements', to='hotel.room', verbose_name='Номер'),
        ),
        migrations.AlterField(
            model_name='placement',
            name='status',
            field=models.CharField(choices=[('waiting', 'Ожидает заезда'), ('active', 'Проживает'), ('finished', 'Выехал')], default='waiting', max_length=30, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='room',
            name='amenities',
            field=models.TextField(blank=True, null=True, verbose_name='Удобства'),
        ),
        migrations.AlterField(
            model_name='room',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='hotel.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='room',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='room',
            name='features',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Особенности'),
        ),
        migrations.AlterField(
            model_name='room',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена за сутки'),
        ),
        migrations.AlterField(
            model_name='room',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Рейтинг'),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_number',
            field=models.CharField(max_length=10, unique=True, verbose_name='Номер комнаты'),
        ),
        migrations.AlterField(
            model_name='room',
            name='rules',
            field=models.TextField(verbose_name='Правила проживания'),
        ),
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('available', 'Свободен'), ('occupied', 'Занят'), ('maintenance', 'На уборке/ремонте')], default='available', max_length=30, verbose_name='Статус'),
        ),
    ]
