# Generated by Django 6.0.5 on 2026-05-26 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_alter_booking_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='yookassa_payment_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID платежа ЮKassa'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(default='yookassa', max_length=50, verbose_name='Способ оплаты'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидание'), ('paid', 'Оплачено'), ('canceled', 'Отменено')], default='pending', max_length=30, verbose_name='Статус'),
        ),
    ]
