# Generated by Django 6.0.5 on 2026-05-06 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_alter_booking_status_alter_booking_user_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='placement',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('guest', 'Guest'), ('admin', 'Admin'), ('staff', 'Staff')], default='guest', max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='placement',
            name='price_per_night',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
